//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ase_Software.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarEntities1 : DbContext
    {
        public CarEntities1()
            : base("name=CarEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<mecanico> mecanico { get; set; }
        public virtual DbSet<repuesto> repuesto { get; set; }
        public virtual DbSet<repuesto_servicio> repuesto_servicio { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    
        public virtual int SP_INS_CLIENTE(string nUM_IDENTIFICACION, string nOMBRE_COMPLETO, string sEXO, string tELEFONO, string dIRECCION, string cIUDAD, string eMAIL, string eSTADO)
        {
            var nUM_IDENTIFICACIONParameter = nUM_IDENTIFICACION != null ?
                new ObjectParameter("NUM_IDENTIFICACION", nUM_IDENTIFICACION) :
                new ObjectParameter("NUM_IDENTIFICACION", typeof(string));
    
            var nOMBRE_COMPLETOParameter = nOMBRE_COMPLETO != null ?
                new ObjectParameter("NOMBRE_COMPLETO", nOMBRE_COMPLETO) :
                new ObjectParameter("NOMBRE_COMPLETO", typeof(string));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var cIUDADParameter = cIUDAD != null ?
                new ObjectParameter("CIUDAD", cIUDAD) :
                new ObjectParameter("CIUDAD", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_CLIENTE", nUM_IDENTIFICACIONParameter, nOMBRE_COMPLETOParameter, sEXOParameter, tELEFONOParameter, dIRECCIONParameter, cIUDADParameter, eMAILParameter, eSTADOParameter);
        }
    
        public virtual int SP_INS_MECANICO(string nOMBRE_COMPLETO, string eSTADO, string sEXO, string tELEFONO, string dIRECCION, string eMAIL)
        {
            var nOMBRE_COMPLETOParameter = nOMBRE_COMPLETO != null ?
                new ObjectParameter("NOMBRE_COMPLETO", nOMBRE_COMPLETO) :
                new ObjectParameter("NOMBRE_COMPLETO", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_MECANICO", nOMBRE_COMPLETOParameter, eSTADOParameter, sEXOParameter, tELEFONOParameter, dIRECCIONParameter, eMAILParameter);
        }
    
        public virtual int SP_INS_REPUESTO(string nOMBRE, string mARCA, Nullable<int> pRECIO_UNIDAD, Nullable<int> sTOCK)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var mARCAParameter = mARCA != null ?
                new ObjectParameter("MARCA", mARCA) :
                new ObjectParameter("MARCA", typeof(string));
    
            var pRECIO_UNIDADParameter = pRECIO_UNIDAD.HasValue ?
                new ObjectParameter("PRECIO_UNIDAD", pRECIO_UNIDAD) :
                new ObjectParameter("PRECIO_UNIDAD", typeof(int));
    
            var sTOCKParameter = sTOCK.HasValue ?
                new ObjectParameter("STOCK", sTOCK) :
                new ObjectParameter("STOCK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_REPUESTO", nOMBREParameter, mARCAParameter, pRECIO_UNIDADParameter, sTOCKParameter);
        }
    
        public virtual int SP_INS_REPUESTO_SERVICIO(Nullable<int> rEPUESTO_ID, Nullable<int> sERVICIO_ID)
        {
            var rEPUESTO_IDParameter = rEPUESTO_ID.HasValue ?
                new ObjectParameter("REPUESTO_ID", rEPUESTO_ID) :
                new ObjectParameter("REPUESTO_ID", typeof(int));
    
            var sERVICIO_IDParameter = sERVICIO_ID.HasValue ?
                new ObjectParameter("SERVICIO_ID", sERVICIO_ID) :
                new ObjectParameter("SERVICIO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_REPUESTO_SERVICIO", rEPUESTO_IDParameter, sERVICIO_IDParameter);
        }
    
        public virtual int SP_INS_SERVICIO(Nullable<int> vEHICULO_ID, string dESCRIPCION_DANO, Nullable<int> mECANICO_ID, Nullable<int> pRESUPESTO_ARREGLO, Nullable<int> eSTIMACION_TIEMPO_HRS, Nullable<int> eSTIMACION_PRECIO, Nullable<int> pRECIO_MANO_OBRA, byte[] fOTO, Nullable<System.DateTime> fECHA_INGRESO, Nullable<System.DateTime> fECHA_SALIDA, string eSTADO)
        {
            var vEHICULO_IDParameter = vEHICULO_ID.HasValue ?
                new ObjectParameter("VEHICULO_ID", vEHICULO_ID) :
                new ObjectParameter("VEHICULO_ID", typeof(int));
    
            var dESCRIPCION_DANOParameter = dESCRIPCION_DANO != null ?
                new ObjectParameter("DESCRIPCION_DANO", dESCRIPCION_DANO) :
                new ObjectParameter("DESCRIPCION_DANO", typeof(string));
    
            var mECANICO_IDParameter = mECANICO_ID.HasValue ?
                new ObjectParameter("MECANICO_ID", mECANICO_ID) :
                new ObjectParameter("MECANICO_ID", typeof(int));
    
            var pRESUPESTO_ARREGLOParameter = pRESUPESTO_ARREGLO.HasValue ?
                new ObjectParameter("PRESUPESTO_ARREGLO", pRESUPESTO_ARREGLO) :
                new ObjectParameter("PRESUPESTO_ARREGLO", typeof(int));
    
            var eSTIMACION_TIEMPO_HRSParameter = eSTIMACION_TIEMPO_HRS.HasValue ?
                new ObjectParameter("ESTIMACION_TIEMPO_HRS", eSTIMACION_TIEMPO_HRS) :
                new ObjectParameter("ESTIMACION_TIEMPO_HRS", typeof(int));
    
            var eSTIMACION_PRECIOParameter = eSTIMACION_PRECIO.HasValue ?
                new ObjectParameter("ESTIMACION_PRECIO", eSTIMACION_PRECIO) :
                new ObjectParameter("ESTIMACION_PRECIO", typeof(int));
    
            var pRECIO_MANO_OBRAParameter = pRECIO_MANO_OBRA.HasValue ?
                new ObjectParameter("PRECIO_MANO_OBRA", pRECIO_MANO_OBRA) :
                new ObjectParameter("PRECIO_MANO_OBRA", typeof(int));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            var fECHA_INGRESOParameter = fECHA_INGRESO.HasValue ?
                new ObjectParameter("FECHA_INGRESO", fECHA_INGRESO) :
                new ObjectParameter("FECHA_INGRESO", typeof(System.DateTime));
    
            var fECHA_SALIDAParameter = fECHA_SALIDA.HasValue ?
                new ObjectParameter("FECHA_SALIDA", fECHA_SALIDA) :
                new ObjectParameter("FECHA_SALIDA", typeof(System.DateTime));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_SERVICIO", vEHICULO_IDParameter, dESCRIPCION_DANOParameter, mECANICO_IDParameter, pRESUPESTO_ARREGLOParameter, eSTIMACION_TIEMPO_HRSParameter, eSTIMACION_PRECIOParameter, pRECIO_MANO_OBRAParameter, fOTOParameter, fECHA_INGRESOParameter, fECHA_SALIDAParameter, eSTADOParameter);
        }
    
        public virtual int SP_INS_VEHICULO(string mARCA, string mODELO, string cOLOR, string aNNO, Nullable<int> pROPIETARIO)
        {
            var mARCAParameter = mARCA != null ?
                new ObjectParameter("MARCA", mARCA) :
                new ObjectParameter("MARCA", typeof(string));
    
            var mODELOParameter = mODELO != null ?
                new ObjectParameter("MODELO", mODELO) :
                new ObjectParameter("MODELO", typeof(string));
    
            var cOLORParameter = cOLOR != null ?
                new ObjectParameter("COLOR", cOLOR) :
                new ObjectParameter("COLOR", typeof(string));
    
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            var pROPIETARIOParameter = pROPIETARIO.HasValue ?
                new ObjectParameter("PROPIETARIO", pROPIETARIO) :
                new ObjectParameter("PROPIETARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_VEHICULO", mARCAParameter, mODELOParameter, cOLORParameter, aNNOParameter, pROPIETARIOParameter);
        }
    
        public virtual int SP_UPDT_CLIENTE(Nullable<int> cLIENTE_ID, string nUM_IDENTIFICACION, string nOMBRE_COMPLETO, string sEXO, string tELEFONO, string dIRECCION, string cIUDAD, string eMAIL, string eSTADO)
        {
            var cLIENTE_IDParameter = cLIENTE_ID.HasValue ?
                new ObjectParameter("CLIENTE_ID", cLIENTE_ID) :
                new ObjectParameter("CLIENTE_ID", typeof(int));
    
            var nUM_IDENTIFICACIONParameter = nUM_IDENTIFICACION != null ?
                new ObjectParameter("NUM_IDENTIFICACION", nUM_IDENTIFICACION) :
                new ObjectParameter("NUM_IDENTIFICACION", typeof(string));
    
            var nOMBRE_COMPLETOParameter = nOMBRE_COMPLETO != null ?
                new ObjectParameter("NOMBRE_COMPLETO", nOMBRE_COMPLETO) :
                new ObjectParameter("NOMBRE_COMPLETO", typeof(string));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var cIUDADParameter = cIUDAD != null ?
                new ObjectParameter("CIUDAD", cIUDAD) :
                new ObjectParameter("CIUDAD", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDT_CLIENTE", cLIENTE_IDParameter, nUM_IDENTIFICACIONParameter, nOMBRE_COMPLETOParameter, sEXOParameter, tELEFONOParameter, dIRECCIONParameter, cIUDADParameter, eMAILParameter, eSTADOParameter);
        }
    
        public virtual int SP_UPDT_MECANICO(Nullable<int> mECANICO_ID, string nOMBRE_COMPLETO, string eSTADO, string sEXO, string tELEFONO, string dIRECCION, string eMAIL)
        {
            var mECANICO_IDParameter = mECANICO_ID.HasValue ?
                new ObjectParameter("MECANICO_ID", mECANICO_ID) :
                new ObjectParameter("MECANICO_ID", typeof(int));
    
            var nOMBRE_COMPLETOParameter = nOMBRE_COMPLETO != null ?
                new ObjectParameter("NOMBRE_COMPLETO", nOMBRE_COMPLETO) :
                new ObjectParameter("NOMBRE_COMPLETO", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDT_MECANICO", mECANICO_IDParameter, nOMBRE_COMPLETOParameter, eSTADOParameter, sEXOParameter, tELEFONOParameter, dIRECCIONParameter, eMAILParameter);
        }
    
        public virtual int SP_UPDT_REPUESTO(Nullable<int> rEPUESTO_ID, string nOMBRE, string mARCA, Nullable<int> pRECIO_UNIDAD, Nullable<int> sTOCK)
        {
            var rEPUESTO_IDParameter = rEPUESTO_ID.HasValue ?
                new ObjectParameter("REPUESTO_ID", rEPUESTO_ID) :
                new ObjectParameter("REPUESTO_ID", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var mARCAParameter = mARCA != null ?
                new ObjectParameter("MARCA", mARCA) :
                new ObjectParameter("MARCA", typeof(string));
    
            var pRECIO_UNIDADParameter = pRECIO_UNIDAD.HasValue ?
                new ObjectParameter("PRECIO_UNIDAD", pRECIO_UNIDAD) :
                new ObjectParameter("PRECIO_UNIDAD", typeof(int));
    
            var sTOCKParameter = sTOCK.HasValue ?
                new ObjectParameter("STOCK", sTOCK) :
                new ObjectParameter("STOCK", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDT_REPUESTO", rEPUESTO_IDParameter, nOMBREParameter, mARCAParameter, pRECIO_UNIDADParameter, sTOCKParameter);
        }
    
        public virtual int SP_UPDT_SERVICIO(Nullable<int> sERVICIO_ID, Nullable<int> vEHICULO_ID, string dESCRIPCION_DANO, Nullable<int> mECANICO_ID, Nullable<int> pRESUPESTO_ARREGLO, Nullable<int> eSTIMACION_TIEMPO_HRS, Nullable<int> eSTIMACION_PRECIO, Nullable<int> pRECIO_MANO_OBRA, byte[] fOTO, Nullable<System.DateTime> fECHA_INGRESO, Nullable<System.DateTime> fECHA_SALIDA, string eSTADO)
        {
            var sERVICIO_IDParameter = sERVICIO_ID.HasValue ?
                new ObjectParameter("SERVICIO_ID", sERVICIO_ID) :
                new ObjectParameter("SERVICIO_ID", typeof(int));
    
            var vEHICULO_IDParameter = vEHICULO_ID.HasValue ?
                new ObjectParameter("VEHICULO_ID", vEHICULO_ID) :
                new ObjectParameter("VEHICULO_ID", typeof(int));
    
            var dESCRIPCION_DANOParameter = dESCRIPCION_DANO != null ?
                new ObjectParameter("DESCRIPCION_DANO", dESCRIPCION_DANO) :
                new ObjectParameter("DESCRIPCION_DANO", typeof(string));
    
            var mECANICO_IDParameter = mECANICO_ID.HasValue ?
                new ObjectParameter("MECANICO_ID", mECANICO_ID) :
                new ObjectParameter("MECANICO_ID", typeof(int));
    
            var pRESUPESTO_ARREGLOParameter = pRESUPESTO_ARREGLO.HasValue ?
                new ObjectParameter("PRESUPESTO_ARREGLO", pRESUPESTO_ARREGLO) :
                new ObjectParameter("PRESUPESTO_ARREGLO", typeof(int));
    
            var eSTIMACION_TIEMPO_HRSParameter = eSTIMACION_TIEMPO_HRS.HasValue ?
                new ObjectParameter("ESTIMACION_TIEMPO_HRS", eSTIMACION_TIEMPO_HRS) :
                new ObjectParameter("ESTIMACION_TIEMPO_HRS", typeof(int));
    
            var eSTIMACION_PRECIOParameter = eSTIMACION_PRECIO.HasValue ?
                new ObjectParameter("ESTIMACION_PRECIO", eSTIMACION_PRECIO) :
                new ObjectParameter("ESTIMACION_PRECIO", typeof(int));
    
            var pRECIO_MANO_OBRAParameter = pRECIO_MANO_OBRA.HasValue ?
                new ObjectParameter("PRECIO_MANO_OBRA", pRECIO_MANO_OBRA) :
                new ObjectParameter("PRECIO_MANO_OBRA", typeof(int));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            var fECHA_INGRESOParameter = fECHA_INGRESO.HasValue ?
                new ObjectParameter("FECHA_INGRESO", fECHA_INGRESO) :
                new ObjectParameter("FECHA_INGRESO", typeof(System.DateTime));
    
            var fECHA_SALIDAParameter = fECHA_SALIDA.HasValue ?
                new ObjectParameter("FECHA_SALIDA", fECHA_SALIDA) :
                new ObjectParameter("FECHA_SALIDA", typeof(System.DateTime));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDT_SERVICIO", sERVICIO_IDParameter, vEHICULO_IDParameter, dESCRIPCION_DANOParameter, mECANICO_IDParameter, pRESUPESTO_ARREGLOParameter, eSTIMACION_TIEMPO_HRSParameter, eSTIMACION_PRECIOParameter, pRECIO_MANO_OBRAParameter, fOTOParameter, fECHA_INGRESOParameter, fECHA_SALIDAParameter, eSTADOParameter);
        }
    
        public virtual int SP_UPDT_VEHICULO(Nullable<int> vEHICULO_ID, string mARCA, string mODELO, string cOLOR, string aNNO, Nullable<int> pROPIETARIO)
        {
            var vEHICULO_IDParameter = vEHICULO_ID.HasValue ?
                new ObjectParameter("VEHICULO_ID", vEHICULO_ID) :
                new ObjectParameter("VEHICULO_ID", typeof(int));
    
            var mARCAParameter = mARCA != null ?
                new ObjectParameter("MARCA", mARCA) :
                new ObjectParameter("MARCA", typeof(string));
    
            var mODELOParameter = mODELO != null ?
                new ObjectParameter("MODELO", mODELO) :
                new ObjectParameter("MODELO", typeof(string));
    
            var cOLORParameter = cOLOR != null ?
                new ObjectParameter("COLOR", cOLOR) :
                new ObjectParameter("COLOR", typeof(string));
    
            var aNNOParameter = aNNO != null ?
                new ObjectParameter("ANNO", aNNO) :
                new ObjectParameter("ANNO", typeof(string));
    
            var pROPIETARIOParameter = pROPIETARIO.HasValue ?
                new ObjectParameter("PROPIETARIO", pROPIETARIO) :
                new ObjectParameter("PROPIETARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDT_VEHICULO", vEHICULO_IDParameter, mARCAParameter, mODELOParameter, cOLORParameter, aNNOParameter, pROPIETARIOParameter);
        }
    }
}
