//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_ASE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SIGECOREntities : DbContext
    {
        public SIGECOREntities()
            : base("name=SIGECOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<mecanico> mecanico { get; set; }
        public virtual DbSet<repuesto> repuesto { get; set; }
        public virtual DbSet<repuesto_servicio> repuesto_servicio { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    
        public virtual int SPR_INS_CLIENTE(string pI_CCLI_CNOMBRE_COMPLETO, string pI_CCLI_CSEXO, string pI_CCLI_CTELEFONO, string pI_CCLI_CDIRECCION, string pI_CCLI_CCIUDAD, string pI_CCLI_CEMAIL, Nullable<bool> pO_OCREADO)
        {
            var pI_CCLI_CNOMBRE_COMPLETOParameter = pI_CCLI_CNOMBRE_COMPLETO != null ?
                new ObjectParameter("PI_CCLI_CNOMBRE_COMPLETO", pI_CCLI_CNOMBRE_COMPLETO) :
                new ObjectParameter("PI_CCLI_CNOMBRE_COMPLETO", typeof(string));
    
            var pI_CCLI_CSEXOParameter = pI_CCLI_CSEXO != null ?
                new ObjectParameter("PI_CCLI_CSEXO", pI_CCLI_CSEXO) :
                new ObjectParameter("PI_CCLI_CSEXO", typeof(string));
    
            var pI_CCLI_CTELEFONOParameter = pI_CCLI_CTELEFONO != null ?
                new ObjectParameter("PI_CCLI_CTELEFONO", pI_CCLI_CTELEFONO) :
                new ObjectParameter("PI_CCLI_CTELEFONO", typeof(string));
    
            var pI_CCLI_CDIRECCIONParameter = pI_CCLI_CDIRECCION != null ?
                new ObjectParameter("PI_CCLI_CDIRECCION", pI_CCLI_CDIRECCION) :
                new ObjectParameter("PI_CCLI_CDIRECCION", typeof(string));
    
            var pI_CCLI_CCIUDADParameter = pI_CCLI_CCIUDAD != null ?
                new ObjectParameter("PI_CCLI_CCIUDAD", pI_CCLI_CCIUDAD) :
                new ObjectParameter("PI_CCLI_CCIUDAD", typeof(string));
    
            var pI_CCLI_CEMAILParameter = pI_CCLI_CEMAIL != null ?
                new ObjectParameter("PI_CCLI_CEMAIL", pI_CCLI_CEMAIL) :
                new ObjectParameter("PI_CCLI_CEMAIL", typeof(string));
    
            var pO_OCREADOParameter = pO_OCREADO.HasValue ?
                new ObjectParameter("PO_OCREADO", pO_OCREADO) :
                new ObjectParameter("PO_OCREADO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPR_INS_CLIENTE", pI_CCLI_CNOMBRE_COMPLETOParameter, pI_CCLI_CSEXOParameter, pI_CCLI_CTELEFONOParameter, pI_CCLI_CDIRECCIONParameter, pI_CCLI_CCIUDADParameter, pI_CCLI_CEMAILParameter, pO_OCREADOParameter);
        }
    }
}
