//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class repuesto_servicio
    {
        public int repuesto_servicio_id { get; set; }
        public Nullable<int> repuesto_id { get; set; }
        public Nullable<int> servicio_id { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual repuesto repuesto { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
