//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_ASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class repuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public repuesto()
        {
            this.repuesto_servicio = new HashSet<repuesto_servicio>();
        }
    
        public int repuesto_id { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public Nullable<int> precio_unidad { get; set; }
        public Nullable<int> stok { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repuesto_servicio> repuesto_servicio { get; set; }
    }
}
